#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace flappy_bird_2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="A39805")]
	public partial class dbdiemDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertquanlidata(quanlidata instance);
    partial void Updatequanlidata(quanlidata instance);
    partial void Deletequanlidata(quanlidata instance);
    #endregion
		
		public dbdiemDataContext() : 
				base(global::flappy_bird_2.Properties.Settings.Default.A39805ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbdiemDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbdiemDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbdiemDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbdiemDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<quanlidata> quanlidatas
		{
			get
			{
				return this.GetTable<quanlidata>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.quanlidata")]
	public partial class quanlidata : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.DateTime _Lần_chơi;
		
		private string _chế_độ;
		
		private int _điểm;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLần_chơiChanging(System.DateTime value);
    partial void OnLần_chơiChanged();
    partial void Onchế_độChanging(string value);
    partial void Onchế_độChanged();
    partial void OnđiểmChanging(int value);
    partial void OnđiểmChanged();
    #endregion
		
		public quanlidata()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Lần chơi]", Storage="_Lần_chơi", DbType="DateTime NOT NULL", IsPrimaryKey=true)]
		public System.DateTime Lần_chơi
		{
			get
			{
				return this._Lần_chơi;
			}
			set
			{
				if ((this._Lần_chơi != value))
				{
					this.OnLần_chơiChanging(value);
					this.SendPropertyChanging();
					this._Lần_chơi = value;
					this.SendPropertyChanged("Lần_chơi");
					this.OnLần_chơiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[chế độ]", Storage="_chế_độ", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string chế_độ
		{
			get
			{
				return this._chế_độ;
			}
			set
			{
				if ((this._chế_độ != value))
				{
					this.Onchế_độChanging(value);
					this.SendPropertyChanging();
					this._chế_độ = value;
					this.SendPropertyChanged("chế_độ");
					this.Onchế_độChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_điểm", DbType="Int NOT NULL")]
		public int điểm
		{
			get
			{
				return this._điểm;
			}
			set
			{
				if ((this._điểm != value))
				{
					this.OnđiểmChanging(value);
					this.SendPropertyChanging();
					this._điểm = value;
					this.SendPropertyChanged("điểm");
					this.OnđiểmChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
